export default {
    //---------------------pictures--------------
    logo: require('../assets/logo.png'),
    logo_icon: require('../assets/logo_icon.png'),
    background: require('../assets/background.png'),
    queen1_ship1: require('../assets/queen1_ship1.png'),
    queen2: require('../assets/queen2.png'),
    queen3_ship4: require('../assets/queen3_ship4.png'),
    queen4: require('../assets/queen4.png'),
    queen5_ship3: require('../assets/queen5_ship3.png'),
    queen6_ship2: require('../assets/queen6_ship2.png'),
    ship5: require('../assets/ship5.png'),
    ship6: require('../assets/ship6.png'),
    factIcon: require('../assets/factIcon.png'),
    //---------------videos-------------------------------------
    logo_animated: require('../assets/logo_animated.mp4'),
    queen: require('../assets/queen2.mp4'),
    mothership: require('../assets/mothership2.mp4'),
    raygun: require('../assets/raygun2.mp4'),
    yes: require('../assets/yes2.mp4'),
    no: require('../assets/no2.mp4'),
    black_hole: require('../assets/blackHole2.mp4'),
    expansion: require('../assets/expansion2.mp4'),
    chicken: require('../assets/chicken2.mp4'),
    egg: require('../assets/egg2.mp4'),
    fertilize: require('../assets/fertilize2.mp4'),
    eat: require('../assets/eat2.mp4'),
    //--------------fonts------------------------------------
    digital7: require('../assets/digital7mono.ttf'),
    gadugi: require('../assets/gadugi.ttf'),
    nightingale: require('../assets/nightingale.ttf'),
    //-------------------------server------------------------------
    logo_uri: 'https://folk.ntnu.no/davidju/5G/CosmiCounsil_logo.png',
    queen_uri: 'https://folk.ntnu.no/davidju/5G/queen.mp4',
    mothership_uri: 'https://folk.ntnu.no/davidju/5G/mothership.mp4',
    raygun_uri: 'https://folk.ntnu.no/davidju/5G/raygun.mp4',
    yes_uri: 'https://folk.ntnu.no/davidju/5G/yes.mp4',
    no_uri: 'https://folk.ntnu.no/davidju/5G/no.mp4',
    black_hole_uri: 'https://folk.ntnu.no/davidju/5G/blackHole.mp4',
    expansion_uri: 'https://folk.ntnu.no/davidju/5G/expansion.mp4',
    chicken_uri: 'https://folk.ntnu.no/davidju/5G/chicken.mp4',
    egg_uri: 'https://folk.ntnu.no/davidju/5G/egg.mp4',
    fertilize_uri: 'https://folk.ntnu.no/davidju/5G/fertilize.mp4',
    eat_uri: 'https://folk.ntnu.no/davidju/5G/eat.mp4',
}